//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfishaApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class EventTable
    {
        public int EventId { get; set; }
        public string EventName { get; set; }
        public string Info { get; set; }
        public System.DateTime EventDate { get; set; }
        public string EventPlace { get; set; }
        public int Duration { get; set; }
        public string Photo { get; set; }
        public int StatusId { get; set; }
        public int CategoryId { get; set; }
        public string GetPhoto
        {
            get
            {
                if (Photo is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\Images\" + Photo.Trim();
            }
        }
        /// <summary>
        /// Задает цвет фона товара
        /// </summary>
        public string GetColor
        {
            get
            {
                return Status.Color;
            }
        }
        /// <summary>
        /// Текстовое представление активности товара
        /// </summary>
        public string GetStatus
        {
            get
            {
                return $"Состояние: {Status.StatusName}";
            }
        }

        public virtual Category Category { get; set; }
        public virtual Status Status { get; set; }
    }
}
